### ISSUE TITLE
Mobile Responsiveness 

### ISSUE THREAD

**Issue by ayo83** [hector-munachi/Buy-Power-2.0#1]
Nice, Neat and light weight work Bro,
So i want to ask, hope the mobile responsiveness is dope because i notice you didn't write any media query , meaning it's responsive in other screens?

**Comment by hector-munachi** [comment]
Media queries is one thing I haven’t really studied and researched on. But I tested the site and its mobile responsive, I arranged my bootstrap grid to allow that...
